openapi: 3.0.0
info:
  title: Cafe Management System
  version: 1.0.0
  description: API documentation (22 end point)
servers:
  - url: "http://localhost:3000"

paths: {}
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
